name: XM to OpenIPC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setenv
        run: |
          TAG_NAME="latest"
          RELEASE_NAME="OpenIPC Firmware"
          PRERELEASE=true
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV
      - name: Install dependencies
        run: sudo apt-get install u-boot-tools zip
      - name: Checkout
        uses: actions/checkout@v2.3.4     
      - name: Fetch OpenIPC release
        run: |
          wget -q https://github.com/OpenIPC/openipc-2.1/releases/download/latest/openipc.hi3516ev300-br.tgz
          wget -q https://github.com/OpenIPC/openipc-2.1/releases/download/latest/openipc.hi3516ev200-br.tgz
      - name: Create firmwares
        run: |
            export RUN="$GITHUB_WORKSPACE/.github/workflows/_xm2oipc.sh"
            export OUTPUTDIR="$GITHUB_WORKSPACE/out"
            chmod +x $RUN
            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_50H20AI_S38" DEVID="000559A7" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_85H30AI_S38" DEVID="000559B0" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_85HF30T_S38" DEVID="000559CD" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516ev300" TOTALMEM="128M" HARDWARE="HI3516EV300_85H50AI" DEVID="000529B2" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516ev300" TOTALMEM="128M" HARDWARE="HI3516EV300_N80050YA" DEVID="000529D9" FLASH_SIZE="0x1000000" $RUN
        continue-on-error: true
      - name: Create release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            Transition firmware for XiongMai-based boards
          draft: false
          prerelease: ${{ env.PRERELEASE }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          file_glob: true
          tag: ${{ env.TAG_NAME }}
          overwrite: true
#       - name: Setup tmate session
#         if: ${{ failure() }}
#         uses: mxschmitt/action-tmate@v3   
