# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
        run: sudo apt-get install u-boot-tools zip
      - name: Fetch Github Release Assets
        # You may pin to the exact commit or the version.
        # uses: Itsblue/download-release-assets-action@8033582b96241f77e3d9644b0d03d26ba9fa9dcf
        uses: Itsblue/download-release-assets-action@v4
        with:
          # org/repo to download from
          repo: OpenIPC/openipc-2.1
          # Version of the release to download from
          version: latest
          # Pattern of the files in the release to download (regex)
          file: openipc*.tgz
          #path: # optional, default is .
      - name: step
        run: ls
