# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setenv
        run: |
          TAG_NAME="latest"
          RELEASE_NAME="Test Build"
          PRERELEASE=true
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV
      - name: Install dependencies
        run: sudo apt-get install u-boot-tools zip
      - name: Checkout
        uses: actions/checkout@v2.3.4     
      - name: fetch
        run: |
          wget -q https://github.com/OpenIPC/openipc-2.1/releases/download/latest/openipc.hi3516ev300-br.tgz
          wget -q https://github.com/OpenIPC/openipc-2.1/releases/download/latest/openipc.hi3516ev200-br.tgz
      - name: step
        run: |
          ls -la $GITHUB_ACTION_PATH $GITHUB_WORKSPACE
      - name: step2
        run: |
            export RUN="$GITHUB_WORKSPACE/.github/workflows/_xm2oipc.sh"
            export OUTPUTDIR="$GITHUB_WORKSPACE/out"
            chmod +x $RUN
            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_50H20AI_S38" DEVID="000559A7" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_85H30AI_S38" DEVID="000559B0" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_85HF30T_S38" DEVID="000559CD" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516ev300" TOTALMEM="128M" HARDWARE="HI3516EV300_85H50AI" DEVID="000529B2" FLASH_SIZE="0x1000000" $RUN
      - name: Create release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: ${{ env.PRERELEASE }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          file_glob: true
          tag: ${{ env.TAG_NAME }}
          overwrite: true
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3   
